### ISSUE TITLE
Remove limit results.

### ISSUE THREAD

**Issue by Darktuse** [bioinformatics-ua/dicoogle-client-js#6]
When i tried to retrieve more than 100 studies, the result ends with a "... X more items]".
I can't find a option to remove this limit or change it.
Is any way I can change this modifying the code?
Could you help me? 

![imagen](https://user-images.githubusercontent.com/9250061/36763739-993d3d30-1c29-11e8-9663-7854bf544c57.png)

**Comment by Enet4** [comment]
Can you provide the sample code that reproduces the issue? Can't tell for sure without it, but it might just be that you called `console.log(results)` on Node.js, which will print the value for human readability. If you want the program to print everything, you can try `console.log(JSON.stringify(results))` instead.

You may also consider using the separate DIM-based search API [`searchDIM`](https://bioinformatics-ua.github.io/dicoogle-client-js/interfaces/_types_dicoogle_client_d_.dicoogleclient.dicoogleaccess.html#searchdim), which will yield an aggregation of studies by patient.

**Comment by Darktuse** [comment]
Not really a code. Simply using windows prompt after installing dicoogle-client via npm. a example against demo dicoogle server would be 
`dicoogle-query` -p lucene -s "http://demo.dicoogle.com" "Modality:MR AND StudyDate:[20040422 TO `20060422]`
That query left 371 items not displayed.

**Comment by Enet4** [comment]
I see. `dicoogle-query` is not feature-complete on this end, is mostly presented here as an example of usage, not as a first-class application. We appreciate suggestions to improve this binary, although it's not on our priority list.

When `dicoogle-query` is called from something that is not a text terminal, it will print valid JSON with the full content. I'll be adding a flag so that this behaviour can be overridden both ways.

**Comment by Enet4** [comment]
@Darktuse I have published a new version with the `--json` flag. Still, we suggest reconsidering its use. If you wish to make an automated processing pipeline of the search results, a JavaScript program with the actual library can do the orchestration. When it's just to observe the results as an end user, we recommend the web application.

**Comment by Darktuse** [comment]
Thanks. I'll think about this.

**Comment by Enet4** [comment]
I'll be closing this issue, but if you would like to suggest concrete changes to the CLI, feel free to file a new one.
